export type POPUP_NAME =
  | 'popup-root'
  | 'popup-confirm-delete'
  | 'popup-add-doctor'
  | 'popup-add-or-edit-department'
  | 'popup-add-exmination-package'
  | 'popup-add-doctor-to-package'
  | 'popup-package-detail'
  | 'popup-warning-choose-doctor'
  | 'popup-confirm-booking'
  | 'popup-edit-department'
  | 'popup-add-medical-record'
  | 'popup-edit-doctor'
  | 'popup-patient-detail'
  | 'popup-doctor-detail'

export type DRAWER_NAME = 'drawer-root'
